#!/bin/bash

# Controlla se il codespace è quello di Galilei -> 4I-TPSI
if [ "$(gh codespace list --json name -q '.[0].name')" = "fuzzy-spoon-7vpvjg4xr6q5hx4rr" ]
# gh codespace list: Ottiene l'elenco dei codespace disponibili.
# --json name: Filtra solo i nomi dei codespace.
# -q '.[0].name': Usa una query JQ per ottenere il nome del primo codespace.
# fuzzy-spoon-7vpvjg4xr6q5hx4rr è il nome del codespace di Galilei
    then
        echo "Il CodeSpace è quello di Galilei. Lo spengo."
        echo "Il CodeSpace sarà spento. La pagina Web se ne accorgerà tra circa 1 minuto, ma puoi già chiudere la scheda del browser."
        gh codespace stop -c fuzzy-spoon-7vpvjg4xr6q5hx4rr
    else
        echo "Il CodeSpace non è quello di Galilei. Non posso spegnerlo."
fi